#!/bin/bash
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "2021 年7 月1 日，习近平在庆祝中国共产党成立100 周年大会发表重要讲话，我们党历经千锤百炼而朝气蓬勃，一个很重要的原因就是我们始终坚持( )。", "answer": "BD", "options": [{"key": "A", "value": "党的统一领导"}, {"key": "B", "value": "党要管党"}, {"key": "C", "value": "民主集中制"}, {"key": "D", "value": "全面从严治党"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 1/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "2021 年7 月1 日，习近平在庆祝中国共产党成立100 周年大会发重要讲话，新的征程上，用马克思主义观察时代、把握时代、引领时代，继续发展( )。", "answer": "BC", "options": [{"key": "A", "value": "中国特色社会主义"}, {"key": "B", "value": "当代中国马克思主义"}, {"key": "C", "value": "21 世纪马克思主义"}, {"key": "D", "value": "新时代中国特色马克思主义"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 2/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "2021 年7 月1 日，习近平在庆祝中国共产党成立100 周年大会发表重要讲话，中国共产党的领导是( )。", "answer": "ABCD", "options": [{"key": "A", "value": "中国特色社会主义最本质的特征"}, {"key": "B", "value": "中国特色社会主义制度的最大优势"}, {"key": "C", "value": "党和国家的根本所在、命运所在"}, {"key": "D", "value": "全国各族人民的利益所系、命运所系"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 3/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "2021 年7 月1 日，习近平在庆祝中国共产党成立100 周年大会发表重要讲话，新民主主义革命的胜利，彻底( )为实现中华民族伟大复兴创造了根本社会条件。", "answer": "ABCD", "options": [{"key": "A", "value": "结束了旧中国半殖民地半封建社会的历史"}, {"key": "B", "value": "彻底结束了旧中国一盘散沙的局面"}, {"key": "C", "value": "消灭在中国延续几千年的封建制度"}, {"key": "D", "value": "彻底废除了列强强加给中国的不平等条约和帝国主义在中国的一切特权"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 4/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "2021 年7 月1 日，习近平在庆祝中国共产党成立100 周年大会发表重要讲话，为了实现中华民族伟大复兴，中国共产党团结带领中国人民( )。", "answer": "ABCD", "options": [{"key": "A", "value": "浴血奋战、百折不挠，创造了新民主主义革命的伟大成就"}, {"key": "B", "value": "自力更生、发愤图强，创造了社会主义革命和建设的伟大成就"}, {"key": "C", "value": "解放思想、锐意进取，创造了改革开放和社会主义现代化建设的伟大成就"}, {"key": "D", "value": "自信自强、守正创新，创造了新时代中国特色社会主义的伟大成就"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 5/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "2021 年7 月1 日，习近平在庆祝中国共产党成立100 周年大会发表重要讲话，中国产生了共产党，这是开天辟地的大事变，深刻改变了( )。", "answer": "ABD", "options": [{"key": "A", "value": "近代以后中华民族发展的方向和进程"}, {"key": "B", "value": "深刻改变了中国人民和中华民族的前途和命运"}, {"key": "C", "value": "旧中国半殖民地半封建社会的历史"}, {"key": "D", "value": "深刻改变了世界发展的趋势和格局"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 6/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "2021 年11 月16 日，习近平就《中共中央关于党的百年奋斗重大成就和历史经验的决议》起草的有关情况向全会作说明，概括了其具有根本性和长远指导意义的十条历史经验，揭示了:", "answer": "ABCD", "options": [{"key": "A", "value": "党和人民事业不断成功的根本保证"}, {"key": "B", "value": "党始终立于不败之地的力量源泉"}, {"key": "C", "value": "党始终掌握历史主动的根本原因"}, {"key": "D", "value": "党永葆先进性和纯洁性、始终走在时代前列的根本途径"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 7/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "2021 年11 月16 日，习近平就《中共中央关于党的百年奋斗重大成就和历史经验的决议》起草的有关情况向全会作说明，全面总结党的百年奋斗重大成就和历史经验，是郑重的历史性、战略性决策，充分体现:", "answer": "ABD", "options": [{"key": "A", "value": "党牢记初心使命、永葆生机活力的坚强意志和坚定决心"}, {"key": "B", "value": "党深刻把握历史发展规律、始终掌握党和国家事业发展的历史主动和使命担当"}, {"key": "C", "value": "加强党的领导这个马克思主义政党的鲜明特征和政治优势"}, {"key": "D", "value": "党立足当下、着眼未来、注重总结和运用历史经验的高瞻远瞩和深谋远虑"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 8/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "2021 年11 月16 日，习近平就《中共中央关于党的百年奋斗重大成就和历史经验的决议》起草的有关情况向全会作说明，对这次全会决议起草，党中央明确要求着重把握好以下几点:", "answer": "ACD", "options": [{"key": "A", "value": "聚焦总结党的百年奋斗重大成就和历史经验"}, {"key": "B", "value": "突出党的政治建设这个重点"}, {"key": "C", "value": "突出中国特色社会主义新时代这个重点"}, {"key": "D", "value": "对重大事件、重要会议、重要人物的评价注重同党中央已有结论相衔接"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 9/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "2022 年5 月10 日，庆祝中国共产主义青年团成立100 周年大会隆重举行。习近平强调，在新的征程上，( )，( )，是新时代中国青年运动和青年工作必须回答的重大课题。", "answer": "AD", "options": [{"key": "A", "value": "如何更好地把青年团结起来、组织起来、动员起来"}, {"key": "B", "value": "如何坚定青年理想"}, {"key": "C", "value": "为实现共产主义而奋斗"}, {"key": "D", "value": "为实现第二个百年奋斗目标、实现中华民族伟大复兴的中国梦而奋斗"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 10/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "为顺应时代发展，以习近平同志为主要代表的中国共产党人，从理论和实践结合上系统回答了新时代重大时代课题，创立了( )的习近平新时代中国特色社会主义思想。", "answer": "AC", "options": [{"key": "A", "value": "怎样坚持和发展中国特色社会主义"}, {"key": "B", "value": "怎样建设社会主义和建设什么样的党"}, {"key": "C", "value": "坚持和发展什么样的中国特色社会主义"}, {"key": "D", "value": "怎样建设党"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 11/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "习近平新时代中国特色社会主义思想是( )，是对马克思列宁主义毛泽东思想、邓小平理论、“三个代表”重要思想、科学发展观的继承和发展，必须长期坚持并不断发展。", "answer": "ABCD", "options": [{"key": "A", "value": "是马克思主义中国化最新成果"}, {"key": "B", "value": "是党和人民实践经验和集体智慧的结晶"}, {"key": "C", "value": "是中国特色社会主义理论体系的重要组成部分"}, {"key": "D", "value": "是全党全国人民为实现中华民族伟大复兴而奋斗的行动指南"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 12/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "改革开放以来我们取得一切成绩和进步的根本原因，归结起来就是( ).", "answer": "ABCD", "options": [{"key": "A", "value": "开辟了中国特色社会主义道路"}, {"key": "B", "value": "形成了中国特色社会主义理论体系"}, {"key": "C", "value": "确立了中国特色社会主义制度"}, {"key": "D", "value": "发展了中国特色社会主义文化"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 13/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "党在自己的工作中实行群众路线，把党的正确主张变为群众的自觉行动。( )", "answer": "ABCD", "options": [{"key": "A", "value": "一切为了群众"}, {"key": "B", "value": "一切依靠群众"}, {"key": "C", "value": "从群众中来"}, {"key": "D", "value": "到群众中去"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 14/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "中国共产党在领导社会主义事业中，必须坚持以经济建设为中心，促进国民经济发展。( )", "answer": "ABCD", "options": [{"key": "A", "value": "更高质量"}, {"key": "B", "value": "更有效率"}, {"key": "C", "value": "更加公平"}, {"key": "D", "value": "更可持续"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 15/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "中国共产党第二十次全国代表大会主题是：高举中国特色社会主义伟大旗帜，全面贯彻( )自信自强、守正创新，踔厉奋发、勇毅前行，为全面建设社会主义现代化国家、全面推进中华民族伟大复兴而团结奋斗。", "answer": "AC", "options": [{"key": "A", "value": "新时代中国特色社会主义思想"}, {"key": "B", "value": "第二个百年奋斗目标"}, {"key": "C", "value": "弘扬伟大建党精神"}, {"key": "D", "value": "社会主义现代化国家新征程"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 16/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "党的二十大报告指出，要坚持以严的基调强化正风肃纪，锲而不舍落实中央八项规定精神，持续深化纠治“‘四风’”，重点纠治( )、( )，坚决破除( )和( )。", "answer": "ACDF", "options": [{"key": "A", "value": "形式主义"}, {"key": "B", "value": "享乐主义"}, {"key": "C", "value": "官僚主义"}, {"key": "D", "value": "特权思想"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 17/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "习近平总书记在党的二十大报告中指出：全党同志务必( )，务必( )，务必( )，坚定历史自信，增强历史主动，谱写新时代中国特色社会主义更加绚丽的华章。", "answer": "ACD", "options": [{"key": "A", "value": "不忘初心、牢记使命"}, {"key": "B", "value": "自信自强、守正创新"}, {"key": "C", "value": "谦虚谨慎、艰苦奋斗"}, {"key": "D", "value": "敢于斗争、善于斗争"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 18/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "完整准确全面贯彻新发展理念，牢牢把握江西在构建新发展格局中的定位，立足江西的特色和优势，着眼高质量发展、绿色发展、低碳发展等新要求，( )( )( )( )努力在加快革命老区高质量发展上走在前、在推动中部地区崛起上勇争先、在推进长江经济带发展上善作为，奋力谱写中国式现代化江西篇章。", "answer": "ABCD", "options": [{"key": "A", "value": "解放思想"}, {"key": "B", "value": "开拓进取"}, {"key": "C", "value": "扬长补短"}, {"key": "D", "value": "固本兴新"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 19/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "广大青年要坚定不移听党话、跟党走，怀抱梦想又脚踏实地，敢想敢为又善作善成，立志做( )、( )、( )、( )的新时代好青年，让青春在全面建设社会主义现代化国家的火热实践中绽放绚丽之花。", "answer": "ABCD", "options": [{"key": "A", "value": "有理想"}, {"key": "B", "value": "敢担当"}, {"key": "C", "value": "能吃苦"}, {"key": "D", "value": "肯奋斗"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 20/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "党的二十大主题是：( )，自信自强、守正创新，踔厉奋发、勇毅前行，为全面建设社会主义现代化国家、全面推进中华民族伟大复兴而团结奋斗。", "answer": "ABC", "options": [{"key": "A", "value": "高举中国特色社会主义伟大旗帜"}, {"key": "B", "value": "全面贯彻新时代中国特色社会主义思想"}, {"key": "C", "value": "弘扬伟大建党精神"}, {"key": "D", "value": "不忘初心、牢记使命"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 21/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "全党同志( )，坚定历史自信，增强历史主动，谱写新时代中国特色社会主义更加绚丽的华章。", "answer": "ABD", "options": [{"key": "A", "value": "务必不忘初心、牢记使命"}, {"key": "B", "value": "务必谦虚谨慎、艰苦奋斗"}, {"key": "C", "value": "务必不骄不躁、砥砺前行"}, {"key": "D", "value": "务必敢于斗争、善于斗争"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 22/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "从党的十八大召开至今，十年来我们经历了对党和人民事业具有重大现实意义和深远历史意义的三件大事：一是( )，二是( )，三是( )，实现第一个百年奋斗目标。", "answer": "BCD", "options": [{"key": "A", "value": "全面深化改革取得重大突破"}, {"key": "B", "value": "迎来中国共产党成立一百周年"}, {"key": "C", "value": "中国特色社会主义进入新时代"}, {"key": "D", "value": "完成脱贫攻坚、全面建成小康社会的历史任务"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 23/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "党的二十大报告指出，要坚持和加强党中央集中统一领导，健全( )的党的领导制度体系。", "answer": "AC", "options": [{"key": "A", "value": "总揽全局"}, {"key": "B", "value": "统筹各方"}, {"key": "C", "value": "协调各方"}, {"key": "D", "value": "协调全局"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 24/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "党的二十大报告指出，党的理论是( )的理论，人民的创造性实践是理论创新的不竭源泉。", "answer": "BCD", "options": [{"key": "A", "value": "脱离人民"}, {"key": "B", "value": "来自人民"}, {"key": "C", "value": "为了人民"}, {"key": "D", "value": "造福人民"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 25/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "党的二十大报告指出，前进道路上，必须坚持和加强党的全面领导，坚持中国特色社会主义道路，坚持( )，坚持( )，坚持( )。", "answer": "ABC", "options": [{"key": "A", "value": "以人民为中心的发展思想"}, {"key": "B", "value": "深化改革开放"}, {"key": "C", "value": "发扬斗争精神"}, {"key": "D", "value": "高速度发展"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 26/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "党的二十大报告指出，要健全( )的社会治理制度，提升社会治理效能。", "answer": "ABC", "options": [{"key": "A", "value": "共建"}, {"key": "B", "value": "共治"}, {"key": "C", "value": "共享"}, {"key": "D", "value": "共管"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 27/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "中国共产党是( )的先锋队。", "answer": "ABC", "options": [{"key": "A", "value": "中国工人阶级"}, {"key": "B", "value": "中国人民"}, {"key": "C", "value": "中华民族"}, {"key": "D", "value": "中国工农阶级"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 28/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "根据新修订《中国共产党纪律处分条例》规定党的纪律处分工作遵循下列原则( )", "answer": "ABCDE", "options": [{"key": "A", "value": "坚持党要管党、全面从严治党"}, {"key": "B", "value": "党纪面前一律平等"}, {"key": "C", "value": "实事求是"}, {"key": "D", "value": "民主集中制"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 29/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "党员有作风纪律方面的苗头性、倾向性问题或者违犯党纪情节轻微的，可以给予( )( )( )等，或者予以诫勉，不予党纪处分。", "answer": "ABC", "options": [{"key": "A", "value": "谈话提醒"}, {"key": "B", "value": "批评教育"}, {"key": "C", "value": "责令检查"}, {"key": "D", "value": "通报曝光"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 30/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "弘扬伟大( )，坚持( )，贯彻全面( )战略方针；落实新时代党的建设总要求", "answer": "ABC", "options": [{"key": "A", "value": "建党精神"}, {"key": "B", "value": "自我革命"}, {"key": "C", "value": "从严治党"}, {"key": "D", "value": "党的领导"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 31/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "构建社会主义和谐社会是按照( )、充满活力、安定有序、人与自然和谐相处的总要求。", "answer": "BCD", "options": [{"key": "A", "value": "团结一心"}, {"key": "B", "value": "公平正义"}, {"key": "C", "value": "诚信友爱"}, {"key": "D", "value": "民主法治"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 32/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "我国正处于并将长期处于社会主义初级阶段，各项工作都要把( )作为总的出发点和检验标准。", "answer": "BCD", "options": [{"key": "A", "value": "有利于超越资本主义国家"}, {"key": "B", "value": "有利于增强社会主义国家的综合国力"}, {"key": "C", "value": "有利于提高人民的生活水平"}, {"key": "D", "value": "有利于发展社会主义社会的生产力"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 33/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "党的二十届四中全会充分肯定党的二十届三中全会以来中央政治局的工作，强调统筹推进“五位一体”总体布局，“五位一体”包括( )。", "answer": "ABCDE", "options": [{"key": "A", "value": "经济建设"}, {"key": "B", "value": "政治建设"}, {"key": "C", "value": "文化建设"}, {"key": "D", "value": "社会建设"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 34/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "二十届三中全会提出，( )是中国式现代化的基础性、战略性支撑。", "answer": "ABC", "options": [{"key": "A", "value": "教育"}, {"key": "B", "value": "科技"}, {"key": "C", "value": "人才"}, {"key": "D", "value": "法治"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 35/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "全会提出，高质量发展必须( )。", "answer": "ABCD", "options": [{"key": "A", "value": "以新发展理念引领改革"}, {"key": "B", "value": "深化供给侧结构性改革"}, {"key": "C", "value": "完善推动高质量发展激励约束机制"}, {"key": "D", "value": "塑造发展新动能新优势"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 36/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "二十届三中全会提出，( )是发挥社会主义市场经济体制优势的内在要求。", "answer": "AB", "options": [{"key": "A", "value": "科学的宏观调控"}, {"key": "B", "value": "有效的政府治理"}, {"key": "C", "value": "充分的市场自由"}, {"key": "D", "value": "单一的行政管控"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 37/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "开展严肃认真的党内政治生活，是我们党的( )。", "answer": "ABC", "options": [{"key": "A", "value": "优良传统"}, {"key": "B", "value": "鲜明特点"}, {"key": "C", "value": "政治优势"}, {"key": "D", "value": "首要任务"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 38/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "党的二十届四中全会提出“十五五”时期经济社会发展必须遵循的原则有( )。", "answer": "ABCDE", "options": [{"key": "A", "value": "坚持党的全面领导"}, {"key": "B", "value": "坚持人民至上"}, {"key": "C", "value": "坚持高质量发展"}, {"key": "D", "value": "坚持全面深化改革"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 39/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "党章规定，党的干部必须具备的基本条件包括( )。", "answer": "ABCD", "options": [{"key": "A", "value": "忠诚干净担当"}, {"key": "B", "value": "具有共产主义远大理想和中国特色社会主义坚定信念"}, {"key": "C", "value": "坚持解放思想、实事求是"}, {"key": "D", "value": "有强烈的革命事业心和政治责任感"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 40/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "党的二十届四中全会提出“十五五”时期经济社会发展的主要目标有( )。", "answer": "ABCDE", "options": [{"key": "A", "value": "高质量发展取得显著成效"}, {"key": "B", "value": "科技自立自强水平大幅提高"}, {"key": "C", "value": "社会文明程度明显提升"}, {"key": "D", "value": "人民生活品质不断提高"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 41/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "党的二十届四中全会审议通过的《建议》提出，要健全国家安全体系，其重点领域包括( )", "answer": "ABCD", "options": [{"key": "A", "value": "经济安全"}, {"key": "B", "value": "科技安全"}, {"key": "C", "value": "国防安全"}, {"key": "D", "value": "网络安全"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 42/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "党的二十届四中全会要求，要协同推进( )，其根本目的是推动经济社会发展全面绿色转型。", "answer": "ABCD", "options": [{"key": "A", "value": "降碳"}, {"key": "B", "value": "减污"}, {"key": "C", "value": "扩绿"}, {"key": "D", "value": "增长"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 43/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "党的二十届四中全会《建议》提出，“十五五”时期经济社会发展必须遵循的原则包括?( )", "answer": "ABCDE", "options": [{"key": "A", "value": "坚持党的全面领导"}, {"key": "B", "value": "坚持以人民为中心"}, {"key": "C", "value": "坚持新发展理念"}, {"key": "D", "value": "坚持深化改革开放"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 44/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "加快发展新质生产力，需要哪些方面的协同发力?( )", "answer": "ABCDE", "options": [{"key": "A", "value": "科技创新"}, {"key": "B", "value": "产业升级"}, {"key": "C", "value": "要素配置"}, {"key": "D", "value": "绿色发展"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 45/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "在全面推进乡村振兴方面，党的二十届四中全会《建议》提出要学习运用“千万工程”经验，其核心要义包括?( )", "answer": "ABCD", "options": [{"key": "A", "value": "因地制宜"}, {"key": "B", "value": "循序渐进"}, {"key": "C", "value": "久久为功"}, {"key": "D", "value": "统筹推进城乡融合发展"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 46/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "党的二十届四中全会《建议》在文化建设方面，提出要健全哪些方面的体制机制?( )", "answer": "ABCD", "options": [{"key": "A", "value": "以社会主义核心价值观引领文化建设的制度"}, {"key": "B", "value": "人民文化权益保障制度"}, {"key": "C", "value": "把社会效益放在首位、社会效益和经济效益相统一的文化创作生产体制机制"}, {"key": "D", "value": "网络内容生态治理机制"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 47/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "党的二十届四中全会《建议》在区域协调发展方面，重点推动哪些区域重大战略?( )", "answer": "ABCDE", "options": [{"key": "A", "value": "京津冀协同发展"}, {"key": "B", "value": "长江经济带发展"}, {"key": "C", "value": "粤港澳大湾区建设"}, {"key": "D", "value": "长三角一体化发展"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 48/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "坚持党中央集中统一领导是最高政治原则，系统完善党的领导制度体系，全党增强“四个意识”，自觉在思想上政治上行动上同党中央保持高度一致，不断提高( )。", "answer": "ABD", "options": [{"key": "A", "value": "政治判断力"}, {"key": "B", "value": "政治领悟力"}, {"key": "C", "value": "政治领导力"}, {"key": "D", "value": "政治执行力"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 49/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "十八大以来，我们党勇于进行理论探索和创新，以全新的视野深化对( )的认识，取得系列理论创新成果，集中体现为新时代中国特色社会主义思想。", "answer": "ACD", "options": [{"key": "A", "value": "共产党执政规律"}, {"key": "B", "value": "共产主义建设规律"}, {"key": "C", "value": "社会主义建设规律"}, {"key": "D", "value": "人类社会发展规律"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 50/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "党的基层组织，根据工作需要和党员人数，经上级党组织批准，分别设立党的( )。", "answer": "ABC", "options": [{"key": "A", "value": "基层委员会"}, {"key": "B", "value": "总支部委员会"}, {"key": "C", "value": "支部委员会"}, {"key": "D", "value": "中央委员会"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 51/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "以下属于党的组织生活的是( )", "answer": "ABCD", "options": [{"key": "A", "value": "“三会一课”"}, {"key": "B", "value": "民主生活会和组织生活会"}, {"key": "C", "value": "谈心谈话"}, {"key": "D", "value": "民主评议党员"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 52/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "党的组织生活是党内政治生活的重要内容和载体，是党组织对党员进行教育管理监督的重要形式。必须坚持党的组织生活各项制度，创新方式方法，增强党的组织生活活力。下列属于党的组织生活制度的有：( )。", "answer": "ABD", "options": [{"key": "A", "value": "“三会一课”制度"}, {"key": "B", "value": "民主生活会和组织生活会制度"}, {"key": "C", "value": "民意调查制度"}, {"key": "D", "value": "谈心谈话制度"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 53/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "与时俱进，就是党的全部理论和工作要( )。", "answer": "ACD", "options": [{"key": "A", "value": "表达时代性"}, {"key": "B", "value": "具有战略性"}, {"key": "C", "value": "富于创造性"}, {"key": "D", "value": "把握规律性"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 54/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "《中国共产党章程》指出，强化管党治党( )和( )，加强对党的领导机关和党员领导干部特别是主要领导干部的监督，不断完善党内监督体系。", "answer": "AC", "options": [{"key": "A", "value": "主体责任"}, {"key": "B", "value": "领导责任"}, {"key": "C", "value": "监督责任"}, {"key": "D", "value": "管理责任"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 55/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "年满十八的中国( )知识分子和其他社会阶层的先进分子，成认党的纲领和章程，愿意参加党的一个组织并在其中积极工作，执行党的决议，和按期交纳党费的，可以申请参加中国共产党。", "answer": "ACD", "options": [{"key": "A", "value": "工人"}, {"key": "B", "value": "商人"}, {"key": "C", "value": "军人"}, {"key": "D", "value": "农民"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 56/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "( )都必须经支部大会讨论通过并报上级党委批准。", "answer": "ABC", "options": [{"key": "A", "value": "延长预备期"}, {"key": "B", "value": "按期转正"}, {"key": "C", "value": "取消预备党员资格"}, {"key": "D", "value": "确定为入党开展对象"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 57/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "政治审查的基本方法是：( )。", "answer": "ABCD", "options": [{"key": "A", "value": "同本人谈话"}, {"key": "B", "value": "查阅有关档案材料"}, {"key": "C", "value": "找有关单位和人员了解"}, {"key": "D", "value": "必要的函调或外调"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 58/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "党的上下级组织之间要做到的是( )", "answer": "ABD", "options": [{"key": "A", "value": "上级组织要经常听取下级组织和党员群众的意见"}, {"key": "B", "value": "下级组织既要向上级组织请示和报告工作"}, {"key": "C", "value": "下级组织要向上级组织求助解决自己职责范围内的问题"}, {"key": "D", "value": "上下级组织之间要互通情报、互相支持和互相监督"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 59/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "中国共产党历史上的两大伟大转折点是( )。", "answer": "BC", "options": [{"key": "A", "value": "八七会议"}, {"key": "B", "value": "遵义会议"}, {"key": "C", "value": "十一届三中全会"}, {"key": "D", "value": "九一会议"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 60/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "“两个确立”反映了全党全军全国各族人民共同心愿，对新时代党和国家事业发展、对推进中华民族伟大复兴历史进程具有决定性意义。“两个确立”是指( )。", "answer": "CD", "options": [{"key": "A", "value": "确立党在社会主义初级阶段的基本路线"}, {"key": "B", "value": "确立“一个中心、两个基本点”"}, {"key": "C", "value": "确立习近平同志党中央的核心、全党的核心地位"}, {"key": "D", "value": "确立习近平新时代中国特色社会主义思想的指导地位"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 61/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "党的各级委员会实行集体领导和个人分工负责相结合的制度。凡属重大问题都要按照集体领导、( )、( )、( )的原则，由党的委员会集体讨论，作出决定；委员会成员要根据集体的决定和分工，切实履行自己的职责。", "answer": "ABD", "options": [{"key": "A", "value": "民主集中"}, {"key": "B", "value": "个别酝酿"}, {"key": "C", "value": "随机应变"}, {"key": "D", "value": "会议决定"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 62/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "党员个人代表党组织发表重要主张，如果超出党组织已有决定的范围，必须提交所在的党组织( )。", "answer": "CD", "options": [{"key": "A", "value": "申请"}, {"key": "B", "value": "汇报"}, {"key": "C", "value": "讨论决定"}, {"key": "D", "value": "向上级党组织请示"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 63/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "党的二十大确立了全面建成社会主义现代化强国、实现第二个百年奋斗目标，以中国式现代化全面推进中华民族伟大复兴的中心任务，阐述了中国式现代化的( )、( )、( )等，对推进中国式现代化作出战略部署。", "answer": "ACD", "options": [{"key": "A", "value": "中国特色"}, {"key": "B", "value": "现实困境"}, {"key": "C", "value": "本质要求"}, {"key": "D", "value": "重大原则"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 64/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "人民政协作为中国共产党领导的政治组织，由具有共同政治基础和奋斗目标的各党派团体和各族各界人士参加，开展( )、( )、( )，有利于完善人民当家作主的制度体系，更好保障最广大人民整体利益、根本利益、长远利益。", "answer": "ACD", "options": [{"key": "A", "value": "政治协商"}, {"key": "B", "value": "依法立法"}, {"key": "C", "value": "民主监督"}, {"key": "D", "value": "参政议政"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 65/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "《党章》指出，( )是关系党生死存亡的问题。", "answer": "AC", "options": [{"key": "A", "value": "党风问题"}, {"key": "B", "value": "脱离群众问题"}, {"key": "C", "value": "党同人民群众联系问题"}, {"key": "D", "value": "腐败问题"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 66/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "下列关于预备党员的说法正确的是( )。", "answer": "ABD", "options": [{"key": "A", "value": "预备党员的预备期为一年"}, {"key": "B", "value": "预备党员的义务同正式党员一样"}, {"key": "C", "value": "预备党员的权利，除了没有选举权和被选举权以外，也同正式党员一样"}, {"key": "D", "value": "预备党员的预备期，从支部大会通过他为预备党员之日算起"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 67/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "聚焦发展全过程人民民主，坚持( )、( )、( )有机统一，推动人民当家作主制度更加健全、协商民主广泛多层制度化发展、中国特色社会主义法治体系更加完善，社会主义法治国家建设达到更高水平。", "answer": "BCD", "options": [{"key": "A", "value": "中国特色社会主义制度"}, {"key": "B", "value": "党的领导"}, {"key": "C", "value": "人民当家作主"}, {"key": "D", "value": "依法治国"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 68/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "共产党员要坚持贯彻党在社会主义初级阶段的基本路线。党的基本路线是党在现阶段的( )。", "answer": "ACD", "options": [{"key": "A", "value": "总任务"}, {"key": "B", "value": "总设计"}, {"key": "C", "value": "总方针"}, {"key": "D", "value": "总政策"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 69/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "党员有接受党的教育培训权，有权提出教育培训要求，参加党组织安排的集中学习教育、( )。", "answer": "ABCD", "options": [{"key": "A", "value": "专题学习教育"}, {"key": "B", "value": "集中轮训"}, {"key": "C", "value": "脱产培训"}, {"key": "D", "value": "网络培训"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 70/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "( )的党员仍然有选举权。", "answer": "ABC", "options": [{"key": "A", "value": "受警告"}, {"key": "B", "value": "严重警告"}, {"key": "C", "value": "撤销党内职务处分"}, {"key": "D", "value": "候补委员"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 71/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "党员履行义务是保证党的( )贯彻执行的需要。", "answer": "BCD", "options": [{"key": "A", "value": "基本思想"}, {"key": "B", "value": "基本理论"}, {"key": "C", "value": "基本路线"}, {"key": "D", "value": "基本纲领"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 72/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "党的纲领包括( )、党在当前历史阶段的总任务和基本政策，以及党的建设的基本要求等。", "answer": "ABCD", "options": [{"key": "A", "value": "党的性质"}, {"key": "B", "value": "党的指导思想"}, {"key": "C", "value": "党的最终目标"}, {"key": "D", "value": "党的根本宗旨"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 73/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "党的纪律的主要特点有( )。", "answer": "ABCD", "options": [{"key": "A", "value": "自觉性"}, {"key": "B", "value": "义务性"}, {"key": "C", "value": "严格性"}, {"key": "D", "value": "统一性"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 74/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "属于“四个意识”的是( )。", "answer": "ACD", "options": [{"key": "A", "value": "政治意识"}, {"key": "B", "value": "全局意识"}, {"key": "C", "value": "核心意识"}, {"key": "D", "value": "看齐意识"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 75/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "党的二十届四中全会充分肯定党的二十届三中全会以来中央政治局的工作，指出中央政治局统筹推进的“五位一体”总体布局包括( )。", "answer": "ABCE", "options": [{"key": "A", "value": "经济建设"}, {"key": "B", "value": "政治建设"}, {"key": "C", "value": "文化建设"}, {"key": "D", "value": "精神文明建设"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 76/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "党的二十届四中全会高度评价“十四五”时期我国发展取得的重大成就，包括( )。", "answer": "ABC", "options": [{"key": "A", "value": "经济实力、科技实力、综合国力跃上新台阶"}, {"key": "B", "value": "中国式现代化迈出新的坚实步伐"}, {"key": "C", "value": "第二个百年奋斗目标新征程实现良好开局"}, {"key": "D", "value": "全面实现社会主义现代化"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 77/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "党的二十届四中全会指出，加快高水平科技自立自强的举措包括( )。", "answer": "ABC", "options": [{"key": "A", "value": "加强原始创新和关键核心技术攻关"}, {"key": "B", "value": "推动科技创新和产业创新深度融合"}, {"key": "C", "value": "深入推进数字中国建设"}, {"key": "D", "value": "依赖国外核心技术"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 78/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "党的二十届四中全会提出“建设现代化产业体系”，具体包括( )。", "answer": "ABCD", "options": [{"key": "A", "value": "加快建设制造强国、质量强国"}, {"key": "B", "value": "加快建设航天强国、交通强国、网络强国"}, {"key": "C", "value": "优化提升传统产业"}, {"key": "D", "value": "培育壮大新兴产业和未来产业"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 79/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "“十五五”规划建议提出建设现代化产业体系需坚持的发展方向包括( )。", "answer": "ABC", "options": [{"key": "A", "value": "智能化"}, {"key": "B", "value": "绿色化"}, {"key": "C", "value": "融合化"}, {"key": "D", "value": "规模化"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 80/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "“十五五”规划建议提出扩大有效投资需优化政府投资结构，重点投向的领域包括( )。", "answer": "ABC", "options": [{"key": "A", "value": "民生类项目"}, {"key": "B", "value": "国家重大战略实施项目"}, {"key": "C", "value": "重点领域安全能力项目"}, {"key": "D", "value": "房地产开发项目"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 81/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "“十五五”时期推进宜居宜业和美乡村建设的关键举措包括( )。", "answer": "ABC", "options": [{"key": "A", "value": "学习运用“千万工程”经验"}, {"key": "B", "value": "片区化推进乡村振兴"}, {"key": "C", "value": "完善乡村建设实施机制"}, {"key": "D", "value": "一刀切推进农村改造"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 82/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "“十五五”时期经济社会发展的主要目标包括( )。", "answer": "ABC", "options": [{"key": "A", "value": "科技自立自强水平大幅提高"}, {"key": "B", "value": "社会文明程度明显提升"}, {"key": "C", "value": "美丽中国建设取得新的重大进展"}, {"key": "D", "value": "基本实现社会主义现代化"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 83/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "“十五五”时期构建强大国内市场的举措包括( )。", "answer": "ABC", "options": [{"key": "A", "value": "大力提振消费"}, {"key": "B", "value": "扩大有效投资"}, {"key": "C", "value": "破除阻碍全国统一大市场建设卡点堵点"}, {"key": "D", "value": "减少公共服务支出"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 84/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "“十五五”时期乡村全面振兴的重点工作有( )。", "answer": "ABC", "options": [{"key": "A", "value": "提升农业综合生产能力和质量效益"}, {"key": "B", "value": "推进宜居宜业和美乡村建设"}, {"key": "C", "value": "提高强农惠农富农政策效能"}, {"key": "D", "value": "减少农村公共服务供给"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 85/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "“十五五”时期经济社会发展全面绿色转型的举措包括( )。", "answer": "ABC", "options": [{"key": "A", "value": "推进污染防治攻坚"}, {"key": "B", "value": "加快建设新型能源体系"}, {"key": "C", "value": "积极稳妥推进和实现碳达峰"}, {"key": "D", "value": "扩大高耗能产业规模"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 86/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "开展严肃认真的党内政治生活，是我们党的( )。", "answer": "ABC", "options": [{"key": "A", "value": "优良传统"}, {"key": "B", "value": "鲜明特点"}, {"key": "C", "value": "政治优势"}, {"key": "D", "value": "首要任务"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 87/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "在长期实践中，我们党坚持把开展严肃认真的党内政治生活作为党的建设重要任务来抓，形成了以实事求是、( )、严明党的纪律等为主要内容的党内政治生活基本规范。", "answer": "ABCD", "options": [{"key": "A", "value": "理论联系实际"}, {"key": "B", "value": "密切联系群众"}, {"key": "C", "value": "批评和自我批评"}, {"key": "D", "value": "民主集中制"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 88/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "新形势下加强和规范党内政治生活，要坚持党的( )，着力增强党内政治生活的政治性、时代性、原则性、战斗性，着力增强党自我净化、自我完善、自我革新、自我提高能力。", "answer": "ABCD", "options": [{"key": "A", "value": "政治路线"}, {"key": "B", "value": "思想路线"}, {"key": "C", "value": "组织路线"}, {"key": "D", "value": "群众路线"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 89/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "必须全面贯彻执行党的基本路线，把以经济建设为中心同( )这两个基本点统一于中国特色社会主义伟大实践，任何时候都不能有丝毫偏离和动摇。", "answer": "CD", "options": [{"key": "A", "value": "坚定理想信念"}, {"key": "B", "value": "坚持党中央的集中统一领导"}, {"key": "C", "value": "坚持四项基本原则"}, {"key": "D", "value": "坚持改革开放"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 90/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "坚持四项基本原则，根本是坚持党的领导，坚持中国特色社会主义道路、( )。", "answer": "ABD", "options": [{"key": "A", "value": "中国特色社会主义理论体系"}, {"key": "B", "value": "中国特色社会主义制度"}, {"key": "C", "value": "中国特色社会主义信念"}, {"key": "D", "value": "中国特色社会主义文化"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 91/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "全党必须牢固树立( )，自觉在思想上政治上行动上同党中央保持高度一致。", "answer": "ABCD", "options": [{"key": "A", "value": "政治意识"}, {"key": "B", "value": "大局意识"}, {"key": "C", "value": "核心意识"}, {"key": "D", "value": "看齐意识"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 92/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "各级党委(党组)必须坚持集体领导制度，凡属重大问题，要按照( )的原则，由集体讨论、按少数服从多数作出决定。", "answer": "ABCD", "options": [{"key": "A", "value": "集体领导"}, {"key": "B", "value": "民主集中"}, {"key": "C", "value": "个别酝酿"}, {"key": "D", "value": "会议决定"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 93/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "全党必须自觉防止和反对( )。", "answer": "ABCD", "options": [{"key": "A", "value": "个人主义"}, {"key": "B", "value": "分散主义"}, {"key": "C", "value": "自由主义"}, {"key": "D", "value": "本位主义"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 94/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "中央委员会、中央政治局、中央政治局常务委员会和党的各级委员会作出重大决策部署，必须深入开展调查研究，广泛听取各方面意见和建议，凝聚智慧和力量，做到( )。", "answer": "ABC", "options": [{"key": "A", "value": "科学决策"}, {"key": "B", "value": "民主决策"}, {"key": "C", "value": "依法决策"}, {"key": "D", "value": "全员决策"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 95/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "坚持“三会一课”制度，坚持( )，坚持谈心谈话制度，坚持对党员进行民主评议。", "answer": "BC", "options": [{"key": "A", "value": "“两学一做”"}, {"key": "B", "value": "民主生活会"}, {"key": "C", "value": "组织生活会制度"}, {"key": "D", "value": "批评与自我批评"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 96/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "政党的先进性不是抽象的，而是( )，是与时代的变化紧密相连的。", "answer": "ABC", "options": [{"key": "A", "value": "历史的"}, {"key": "B", "value": "具体的"}, {"key": "C", "value": "现实的"}, {"key": "D", "value": "永恒的"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 97/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "党的纯洁性体现在党的( )各个方面。", "answer": "ABCD", "options": [{"key": "A", "value": "思想"}, {"key": "B", "value": "政治"}, {"key": "C", "value": "组织"}, {"key": "D", "value": "作风"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 98/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "党的理论、路线、纲领、方针、政策和各项工作，必须努力体现发展面向现代化、面向世界、面向未来的，( )社会主义文化的要求。", "answer": "ABCD", "options": [{"key": "A", "value": "先进的"}, {"key": "B", "value": "民族的"}, {"key": "C", "value": "科学的"}, {"key": "D", "value": "大众的"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 99/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "( )，三者紧密相连，不可分割。", "answer": "ACD", "options": [{"key": "A", "value": "共产主义理想"}, {"key": "B", "value": "共产主义理论"}, {"key": "C", "value": "共产主义运动"}, {"key": "D", "value": "共产主义制度"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 100/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "我们党的( )，密切联系群众是我们党的最大政治优势，脱离群众是我们党执政后的最大危险。", "answer": "ABC", "options": [{"key": "A", "value": "根基在人民"}, {"key": "B", "value": "血脉在人民"}, {"key": "C", "value": "力量在人民"}, {"key": "D", "value": "未来在人民"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 101/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "为人民服务应该是( )的。", "answer": "ABCD", "options": [{"key": "A", "value": "与时俱进"}, {"key": "B", "value": "始终如一"}, {"key": "C", "value": "脚踏实地"}, {"key": "D", "value": "具体"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 102/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "我们党领导中国人民进行革命、建设和改革的历史，就是一部群众工作史，就是一部( )的奋斗史。", "answer": "ABCD", "options": [{"key": "A", "value": "动员群众"}, {"key": "B", "value": "组织群众"}, {"key": "C", "value": "团结群众"}, {"key": "D", "value": "依靠群众"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 103/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "“三大战役”的胜利奠定了人民解放战争在全国胜利的基础。“三大战役”是指( )。", "answer": "ACD", "options": [{"key": "A", "value": "辽沈战役"}, {"key": "B", "value": "济南战役"}, {"key": "C", "value": "淮海战役"}, {"key": "D", "value": "平津战役"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 104/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "1981 年中共十一届六中全会通过的《关于建国以来党的若干历史问题的决议》中，全面科学地评论了毛泽东思想，第一次使用了“毛泽东思想的活的灵魂”的表述，指出( )是贯穿于毛泽东思想科学体系各个组成部分的立场、观点和方法。", "answer": "BCD", "options": [{"key": "A", "value": "解放思想"}, {"key": "B", "value": "实事求是"}, {"key": "C", "value": "群众路线"}, {"key": "D", "value": "独立自主"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 105/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "在我国社会主义建设中，毛泽东同志提出了( )的发展社会主义文化的基本方针。", "answer": "CD", "options": [{"key": "A", "value": "洋为中用"}, {"key": "B", "value": "古为今用"}, {"key": "C", "value": "百花齐放"}, {"key": "D", "value": "百家争鸣"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 106/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "1981 年，党的十一届六中全会第一次提出“毛泽东思想活的灵魂”。毛泽东思想活的灵魂是贯穿于毛泽东思想各个组成部分的立场、观点和方法，它有三个基本方面，即( )", "answer": "ABC", "options": [{"key": "A", "value": "实事求是"}, {"key": "B", "value": "独立自主"}, {"key": "C", "value": "群众路线"}, {"key": "D", "value": "人民至上"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 107/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "党的十一届三中全会的深远历史意义主要体现在( )。", "answer": "ABC", "options": [{"key": "A", "value": "结束了粉碎“四人帮”后党和国家的工作在徘徊中前进的局面"}, {"key": "B", "value": "开始了党在思想、政治、组织等领域的全面拨乱反正"}, {"key": "C", "value": "形成了以邓小平同志为核心的中共中央领导集体"}, {"key": "D", "value": "全面恢复了中断多年的高考制度"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 108/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "香港自古以来就是中国的领土，英国通过数次和清政府签订不平等条约，曾占有包括香港岛、九龙半岛和“新界”在内总面积达1092 平方千米的中国领土。这些条约包括( )。", "answer": "ABD", "options": [{"key": "A", "value": "《南京条约》"}, {"key": "B", "value": "《北京条约》"}, {"key": "C", "value": "《天津条约》"}, {"key": "D", "value": "《展拓香港界址专条》"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 109/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "中国共产党的三大优良作风是( )。", "answer": "ABD", "options": [{"key": "A", "value": "理论联系实际"}, {"key": "B", "value": "密切联系群众"}, {"key": "C", "value": "民主集中"}, {"key": "D", "value": "批评与自我批评"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 110/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "习近平总书记在纪念五四运动100 周年大会上的讲话中指出，五四运动，以( )，推进了中国社会进步，促进了马克思主义在中国的传播，促进了马克思主义同中国工人运动的结合。", "answer": "ABD", "options": [{"key": "A", "value": "彻底反帝反封建的革命性"}, {"key": "B", "value": "追求救国强国真理的进步性"}, {"key": "C", "value": "前所未有的斗争性"}, {"key": "D", "value": "各族各界群众积极参与的广泛性"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 111/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "毛泽东思想形成过程中哪些著作创立了其独具特色的军事理论?( )", "answer": "ABC", "options": [{"key": "A", "value": "《抗日游击战争的战略问题》"}, {"key": "B", "value": "《论持久战》"}, {"key": "C", "value": "《战争和战略的问题》"}, {"key": "D", "value": "《反对本本主义》"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 112/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "戊戌维新运动虽然失败了，但它在中国历史上仍然有着重大的历史意义，戊戌维新运动是一次爱国救亡运动，维新派在民族存亡的关键时刻( )。", "answer": "ABD", "options": [{"key": "A", "value": "高举救亡图存的旗帜"}, {"key": "B", "value": "要求通过变法，发展资本主义，使中国走上富强的道路"}, {"key": "C", "value": "成功在中国建立了君主立宪制"}, {"key": "D", "value": "其政治实践和思想理论一定程度上推动了中华民族的觉醒"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 113/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "十八大以来，以习近平同志为主要代表的中国共产党人，坚持把马克思主义基本原理同( )相结合、同( )相结合，科学回答了新时代坚持和发展什么样的中国特色社会主义、怎样坚持和发展中国特色社会主义等重大时代课题，创立了习近平新时代中国特色社会主义思想。", "answer": "AC", "options": [{"key": "A", "value": "中国具体实际"}, {"key": "B", "value": "党情国情世情"}, {"key": "C", "value": "中华优秀传统文化"}, {"key": "D", "value": "世界百年未有之大变局"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 114/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "中国共产党经过长期实践，积累了( )、( )、坚持理论创新、坚持独立自主、坚持中国道路、坚持胸怀天下、坚持开拓创新、( )、坚持统一战线、坚持自我革命的宝贵历史经验，这是党和人民共同创造的精神财富，必须倍加珍惜、长期坚持，并在实践中不断丰富和发展。", "answer": "ABD", "options": [{"key": "A", "value": "坚持党的领导"}, {"key": "B", "value": "坚持人民至上"}, {"key": "C", "value": "坚持人民民主"}, {"key": "D", "value": "坚持敢于斗争"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 115/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "根据二十大党章要求，必须坚持以人民为中心的发展思想，把握新发展阶段，贯彻新发展理念，( )。", "answer": "CD", "options": [{"key": "A", "value": "打造新发展动能"}, {"key": "B", "value": "把握新发展趋势"}, {"key": "C", "value": "构建新发展格局"}, {"key": "D", "value": "推动高质量发展"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 116/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "要协调推进“四个全面”战略布局。“四个全面”即( )。", "answer": "ABCD", "options": [{"key": "A", "value": "全面建设社会主义现代化国家"}, {"key": "B", "value": "全面深化改革"}, {"key": "C", "value": "全面依法治国"}, {"key": "D", "value": "全面从严治党"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 117/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "坚持总体国家安全观，统筹发展和安全，坚决维护国家( )。", "answer": "ACD", "options": [{"key": "A", "value": "主权"}, {"key": "B", "value": "稳定"}, {"key": "C", "value": "安全"}, {"key": "D", "value": "发展利益"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 118/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "中国共产党在国际事务中，弘扬和平、发展、公平、( )、自由的全人类共同价值。", "answer": "AD", "options": [{"key": "A", "value": "正义"}, {"key": "B", "value": "公正"}, {"key": "C", "value": "友善"}, {"key": "D", "value": "民主"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 119/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "二十大党章指出，弘扬( )的伟大建党精神。", "answer": "ABCD", "options": [{"key": "A", "value": "坚持真理、坚守理想"}, {"key": "B", "value": "践行初心、担当使命"}, {"key": "C", "value": "不怕牺牲、英勇斗争"}, {"key": "D", "value": "对党忠诚、不负人民"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 120/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "企业、农村、机关、( )、社会组织、人民解放军连队和其他基层单位，凡是有正式党员3 人以上的，都应当成立党的基层组织。", "answer": "ABCD", "options": [{"key": "A", "value": "学校"}, {"key": "B", "value": "医院"}, {"key": "C", "value": "科研院所"}, {"key": "D", "value": "街道社区"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 121/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "坚持新时代党的组织路线，全党必须增强党组织的( )和( )，培养选拔党和人民需要的好干部，培养和造就大批堪当时代重任的社会主义事业接班人，聚天下英才而用之，从组织上保证党的基本理论、基本路线、基本方略的贯彻落实。", "answer": "BC", "options": [{"key": "A", "value": "宣传功能"}, {"key": "B", "value": "政治功能"}, {"key": "C", "value": "组织功能"}, {"key": "D", "value": "管理功能"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 122/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "二十大党章进一步明确派驻纪律检查组的范围，增写按照规定向有关( )派驻党的纪律检查组的内容。", "answer": "ACD", "options": [{"key": "A", "value": "国有企业"}, {"key": "B", "value": "民营企业"}, {"key": "C", "value": "社会组织"}, {"key": "D", "value": "事业单位"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 123/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "党的二十大报告指出，全党同志( )，坚定历史自信，增强历史主动，谱写新时代中国特色社会主义更加绚丽的华章。", "answer": "ABC", "options": [{"key": "A", "value": "务必不忘初心、牢记使命"}, {"key": "B", "value": "务必谦虚谨慎、艰苦奋斗"}, {"key": "C", "value": "务必敢于斗争、善于斗争"}, {"key": "D", "value": "务必信念坚定、为民服务"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 124/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "我国始终把( )作为处理国际关系的基本准则。", "answer": "AB", "options": [{"key": "A", "value": "和平共处"}, {"key": "B", "value": "互利共赢"}, {"key": "C", "value": "亲诚惠容"}, {"key": "D", "value": "真实亲诚"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 125/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "中国式现代化的本质要求有哪些?", "answer": "ABCD", "options": [{"key": "A", "value": "坚持中国共产党领导"}, {"key": "B", "value": "坚持中国特色社会主义"}, {"key": "C", "value": "实现高质量发展"}, {"key": "D", "value": "实现全体人民共同富裕"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 126/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "习近平新时代中国特色社会主义思想是( )，是中华文化和中国精神的时代精华。", "answer": "BC", "options": [{"key": "A", "value": "新时代中国马克思主义"}, {"key": "B", "value": "当代中国马克思主义"}, {"key": "C", "value": "二十一世纪马克思主义"}, {"key": "D", "value": "马克思主义活的灵魂"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 127/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "全面深化改革总目标包括( )。", "answer": "BC", "options": [{"key": "A", "value": "建立更加科学的国家治理模式和治理体系"}, {"key": "B", "value": "完善和发展中国特色社会主义制度"}, {"key": "C", "value": "推进国家治理体系和治理能力现代化"}, {"key": "D", "value": "继续坚持完善中国特色社会主义道路、制度和理论"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 128/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "统筹城乡发展、区域发展、( )，调整经济结构，转变经济发展方式，推进供给侧结构性改革。", "answer": "BCD", "options": [{"key": "A", "value": "产业平衡发展"}, {"key": "B", "value": "经济社会发展"}, {"key": "C", "value": "人与自然和谐发展"}, {"key": "D", "value": "国内发展和对外开放"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 129/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "党章总纲部分党的建设总体要求中提出了不断增强“四自能力”的要求。“四自能力”是指( )能力。", "answer": "ABCD", "options": [{"key": "A", "value": "自我净化"}, {"key": "B", "value": "自我完善"}, {"key": "C", "value": "自我革新"}, {"key": "D", "value": "自我提高"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 130/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "建设( )的马克思主义执政党。", "answer": "BCD", "options": [{"key": "A", "value": "先进型"}, {"key": "B", "value": "学习型"}, {"key": "C", "value": "服务型"}, {"key": "D", "value": "创新型"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 131/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "新时代党的组织路线要求，坚持( )、任人唯贤。", "answer": "AB", "options": [{"key": "A", "value": "德才兼备"}, {"key": "B", "value": "以德为先"}, {"key": "C", "value": "能上能下"}, {"key": "D", "value": "实绩突出"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 132/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "下列选项中属于学习贯彻习近平新时代中国特色社会主义思想主题教育需着力解决的突出问题的是( )。", "answer": "ABCD", "options": [{"key": "A", "value": "政治素质方面"}, {"key": "B", "value": "廉洁自律方面"}, {"key": "C", "value": "担当作为方面"}, {"key": "D", "value": "工作能力方面"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 133/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "下列选项中属于学习贯彻习近平新时代中国特色社会主义思想主题教育具体要达到的目标的是( )。", "answer": "ABCD", "options": [{"key": "A", "value": "凝心铸魂筑牢根本"}, {"key": "B", "value": "锤炼品格强化担当"}, {"key": "C", "value": "践行宗旨为民造福"}, {"key": "D", "value": "廉洁自律树立新风"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 134/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "文化自信是一个国家、一个民族发展中( )的力量。", "answer": "ABD", "options": [{"key": "A", "value": "最基本"}, {"key": "B", "value": "最深沉"}, {"key": "C", "value": "最重要"}, {"key": "D", "value": "最持久"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 135/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "改革开放应当大胆探索，勇于开拓，提高改革决策的科学性，更加注重改革的( )，在实践中开创新路。", "answer": "ABD", "options": [{"key": "A", "value": "系统性"}, {"key": "B", "value": "整体性"}, {"key": "C", "value": "科学性"}, {"key": "D", "value": "协同性"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 136/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "党的二十大报告指出，实施产业基础再造工程和重大技术装备攻关工程，支持专精特新企业发展，推动制造业( )发展。", "answer": "ABCD", "options": [{"key": "A", "value": "数字化"}, {"key": "B", "value": "高端化"}, {"key": "C", "value": "智能化"}, {"key": "D", "value": "绿色化"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 137/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "新形势下，党面临的“四大考验”是长期的、复杂的、严峻的，“四大考验”是指：执政考验、( )。", "answer": "ABC", "options": [{"key": "A", "value": "改革开放考验"}, {"key": "B", "value": "市场经济考验"}, {"key": "C", "value": "外部环境考验"}, {"key": "D", "value": "科技创新考验"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 138/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "新形势下，精神懈怠危险、( )更加尖锐地摆在全党面前。", "answer": "ABD", "options": [{"key": "A", "value": "能力不足危险"}, {"key": "B", "value": "脱离群众危险"}, {"key": "C", "value": "资源枯竭危险"}, {"key": "D", "value": "消极腐败危险"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 139/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "以下属于党的基层组织基本任务的( )。", "answer": "BCD", "options": [{"key": "A", "value": "选举上级党的委员会"}, {"key": "B", "value": "推进党史学习教育常态化制度化"}, {"key": "C", "value": "对党员进行教育、管理、监督和服务，提高党员素质，坚定理想信念，增强党性"}, {"key": "D", "value": "监督党员干部和其他任何工作人员严格遵守国家法律法规"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 140/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "党的二十大报告指出，( )是社会主义现代化的根本要求。", "answer": "BD", "options": [{"key": "A", "value": "人民幸福"}, {"key": "B", "value": "物质富足"}, {"key": "C", "value": "社会稳定"}, {"key": "D", "value": "精神富有"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 141/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "在“一国两制”中，两种制度的关系是( )。", "answer": "BCD", "options": [{"key": "A", "value": "不分主次、共同发展"}, {"key": "B", "value": "大陆的社会主义制度是主体"}, {"key": "C", "value": "长期共存和平共处"}, {"key": "D", "value": "相互支援"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 142/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "中国共产党领导人民建设社会主义生态文明，树立( )的生态文明理念。", "answer": "BCD", "options": [{"key": "A", "value": "爱护自然"}, {"key": "B", "value": "顺应自然"}, {"key": "C", "value": "保护自然"}, {"key": "D", "value": "尊重自然"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 143/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "我国最广泛的爱国统一战线是由( )组成的。", "answer": "ABCD", "options": [{"key": "A", "value": "全体社会主义劳动者"}, {"key": "B", "value": "社会主义事业的建设者"}, {"key": "C", "value": "拥护社会主义的爱国者"}, {"key": "D", "value": "拥护祖国统一和致力于中华民族伟大复兴的爱国者"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 144/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "党章要求，党员要发扬社会主义新风尚，带头实践( )，为了保护国家和人民的利益，在一切困难和危险的时刻挺身而出，英勇斗争，不怕牺牲。", "answer": "ABCD", "options": [{"key": "A", "value": "社会主义核心价值观"}, {"key": "B", "value": "社会主义荣辱观"}, {"key": "C", "value": "提倡共产主义道德"}, {"key": "D", "value": "弘扬中华民族传统美德"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 145/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "我们要加快构建反映( )的价值体系。", "answer": "BCD", "options": [{"key": "A", "value": "上层建筑"}, {"key": "B", "value": "中国特色"}, {"key": "C", "value": "民族特性"}, {"key": "D", "value": "时代特征"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 146/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "下列属于入党誓词内容的有( )。", "answer": "ABCD", "options": [{"key": "A", "value": "拥护党的纲领"}, {"key": "B", "value": "履行党员义务"}, {"key": "C", "value": "对党忠诚，积极工作"}, {"key": "D", "value": "执行党的决议"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 147/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "在党章中，无论是修改而来的还是保持不变的，都统一于解决“( )”这个根本问题。", "answer": "AB", "options": [{"key": "A", "value": "党是什么"}, {"key": "B", "value": "要干什么"}, {"key": "C", "value": "要怎么干"}, {"key": "D", "value": "为什么干"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 148/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "马克思主义的主要内容包括三个组成部分，即( )。", "answer": "BCD", "options": [{"key": "A", "value": "辩证唯物主义"}, {"key": "B", "value": "马克思主义哲学"}, {"key": "C", "value": "政治经济学"}, {"key": "D", "value": "科学社会主义"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 149/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "发展党员的介绍人要认真了解申请人的( )，向他解释党的纲领和党的章程，并向党组织作出负责的报告。", "answer": "ABCD", "options": [{"key": "A", "value": "思想"}, {"key": "B", "value": "品质"}, {"key": "C", "value": "工作表现"}, {"key": "D", "value": "经历"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 150/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "2021 年7 月1 日，习近平在庆祝中国共产党成立100 周年大会发表重要讲话，我们创造了改革开放和社会主义现代化建设的伟大成就，实现新中国成立以来党的历史上具有深远意义的伟大转折，实现了( )。", "answer": "ABCD", "options": [{"key": "A", "value": "从高度集中的计划经济体制到充满活力的社会主义市场经济体制的历史性转变"}, {"key": "B", "value": "从封闭半封闭到全方位开放的历史性转变"}, {"key": "C", "value": "从生产力相对落后的状况到经济总量跃居世界前三的历史性突破"}, {"key": "D", "value": "人民生活从温饱不足到总体小康、奔向全面小康的历史性跨越"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 151/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "2021 年7 月1 日，习近平在庆祝中国共产党成立100 周年大会发表重要讲话，社会主义革命和建设的伟大成就，为实现中华民族伟大复兴奠定了( )和( )。", "answer": "BC", "options": [{"key": "A", "value": "体制保证"}, {"key": "B", "value": "政治前提"}, {"key": "C", "value": "制度基础"}, {"key": "D", "value": "社会条件"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 152/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "新的征程上，我们必须高举和平，( )，( )，( )旗帜，奉行独立自主的和平外交政策，坚持走和平发展道路，推动建设新型国际关系，推动构建人类命运共同体，推动共建“一带一路”高质量发展，以中国的新发展为世界提供新机遇。", "answer": "ABCD", "options": [{"key": "A", "value": "发展"}, {"key": "B", "value": "公平"}, {"key": "C", "value": "合作"}, {"key": "D", "value": "共赢"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 153/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "新的征程上，我们必须全面贯彻新时代党的强军思想，贯彻新时代军事战略方针，坚持党对人民军队的绝对领导，坚持走中国特色强军之路，全面推进( )、改革强军、科技强军、人才强军、( )，把人民军队建设成为世界一流军队，以更强大的能力、更可靠的手段捍卫国家主权、安全、发展利益!", "answer": "AC", "options": [{"key": "A", "value": "政治建军"}, {"key": "B", "value": "政治强军"}, {"key": "C", "value": "依法治军"}, {"key": "D", "value": "依法建军"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 154/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "新的征程上，确保党( )，确保党在新时代坚持和发展中国特色社会主义的历史进程中始终成为坚强领导核心!", "answer": "ACD", "options": [{"key": "A", "value": "不变质"}, {"key": "B", "value": "不变味"}, {"key": "C", "value": "不变色"}, {"key": "D", "value": "不变腐"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 155/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "中国人民是崇尚正义、不畏强暴的人民，中华民族是具有强烈民族( )的民族。", "answer": "ABD", "options": [{"key": "A", "value": "自尊心"}, {"key": "B", "value": "自豪感"}, {"key": "C", "value": "光荣感"}, {"key": "D", "value": "自信心"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 156/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "党的基层组织的基本任务是( )。", "answer": "ACD", "options": [{"key": "A", "value": "宣传和执行党的路线、方针、政策，宣传和执行党中央、上级组织和本组织的决议"}, {"key": "B", "value": "讨论本地区范围内的重大问题并作出决议"}, {"key": "C", "value": "对要求入党的积极分子进行教育和培养，做好经常性地发展党员工作"}, {"key": "D", "value": "密切联系群众，做好群众的思想政治工作"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 157/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "党的十九大、十九届六中全会提出的( )概括了习近平新时代中国特色社会主义思想的主要内容。", "answer": "ABC", "options": [{"key": "A", "value": "“十个明确”"}, {"key": "B", "value": "“十四个坚持”"}, {"key": "C", "value": "“十三个方面成就”"}, {"key": "D", "value": "第一要务"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 158/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "中国式现代化的本质要求是( )。", "answer": "ABCD", "options": [{"key": "A", "value": "坚持中国共产党领导，坚持中国特色社会主义"}, {"key": "B", "value": "实现高质量发展，发展全过程人民民主"}, {"key": "C", "value": "丰富人民精神世界，实现全体人民共同富裕，促进人与自然和谐共生"}, {"key": "D", "value": "推动构建人类命运共同体，创造人类文明新形态"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 159/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "要扩大人民有序政治参与，保证人民依法实行( )。", "answer": "ABCDE", "options": [{"key": "A", "value": "民主选举"}, {"key": "B", "value": "民主协商"}, {"key": "C", "value": "民主决策"}, {"key": "D", "value": "民主管理"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 160/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "深入推进环境污染防治，持续深入打好( )保卫战。", "answer": "ABC", "options": [{"key": "A", "value": "蓝天"}, {"key": "B", "value": "碧水"}, {"key": "C", "value": "净土"}, {"key": "D", "value": "河清"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 161/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "贯彻新时代军事战略方针，坚持党对人民军队的绝对领导，坚持政治建军( )人才强军、依法治军。", "answer": "BD", "options": [{"key": "A", "value": "发展强军"}, {"key": "B", "value": "改革强军"}, {"key": "C", "value": "战略强军"}, {"key": "D", "value": "科技强军"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 162/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "前进道路上，必须牢牢把握以下重大原则( )。", "answer": "ABCDE", "options": [{"key": "A", "value": "坚持和加强党的全面领导"}, {"key": "B", "value": "坚持中国特色社会主义道路"}, {"key": "C", "value": "坚持以人民为中心的发展思想"}, {"key": "D", "value": "坚持深化改革开放"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 163/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "深入实施人才强国战略，坚持( )完善人才战略布局，加快建设世界重要人才中心和创新高地，着力形成人才国际竞争的比较优势，把各方面优秀人才集聚到党和人民事业中来。", "answer": "ABCD", "options": [{"key": "A", "value": "尊重劳动"}, {"key": "B", "value": "尊重知识"}, {"key": "C", "value": "尊重人才"}, {"key": "D", "value": "尊重创造"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 164/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "( )是全面建设社会主义现代化国家的基础性、战略性支撑。", "answer": "ABD", "options": [{"key": "A", "value": "教育"}, {"key": "B", "value": "科技"}, {"key": "C", "value": "创新"}, {"key": "D", "value": "人才"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 165/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "党的二十大报告指出，要全面推进( )，全面推进国家各方面工作法治化。", "answer": "ABCD", "options": [{"key": "A", "value": "科学立法"}, {"key": "B", "value": "严格执法"}, {"key": "C", "value": "公正司法"}, {"key": "D", "value": "全民守法"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 166/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "中国坚持在和平共处五项原则基础上同各国发展友好合作，推动构建新型国际关系，深化拓展( )的全球伙伴关系，致力于扩大同各国利益的汇合点。", "answer": "ABCD", "options": [{"key": "A", "value": "平等"}, {"key": "B", "value": "共赢"}, {"key": "C", "value": "开放"}, {"key": "D", "value": "合作"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 167/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "党的二十大报告指出，只有把( )同中国( )相结合、同( )相结合，坚持运用辩证唯物主义和历史唯物主义，才能正确回答时代和实践提出的重大问题，才能始终保持马克思主义的蓬勃生机和旺盛活力。", "answer": "ACD", "options": [{"key": "A", "value": "马克思主义基本原理"}, {"key": "B", "value": "新时代中国特色社会主义"}, {"key": "C", "value": "具体实际"}, {"key": "D", "value": "中华优秀传统文化"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 168/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "党的二十大报告指出：必须坚持科技是第一生产力、人才是第一资源、创新是第一动力，深入实施( )，开辟发展新领域新赛道，不断塑造发展新动能新优势。", "answer": "ACD", "options": [{"key": "A", "value": "科教兴国战略"}, {"key": "B", "value": "制造业强国战略"}, {"key": "C", "value": "人才强国战略"}, {"key": "D", "value": "创新驱动发展战略"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 169/170"
curl -s -X POST http://localhost:9091/api/v1/questions -H "Content-Type: application/json" -d '{"type": "multiple_choice", "question": "增强维护国家安全能力，坚定维护国家( )确保粮食、能源资源、重要产业链供应链安全，维护我国公民、法人在海外合法权益，筑牢国家安全人民防线。", "answer": "ABCD", "options": [{"key": "A", "value": "政治安全"}, {"key": "B", "value": "政权安全"}, {"key": "C", "value": "制度安全"}, {"key": "D", "value": "意识形态安全"}], "explanation": ""}' > /dev/null 2>&1
echo "多选题 170/170"
